### ISSUE TITLE
Unable to preprocess data

### ISSUE THREAD

**Issue by charu-iitm** [minsangkim142/Fast-Reading-Comprehension#34]
I am getting following error while preprocessing: 
**Generating word embedding...
 13%|#######################3                                                                                                                                                     | 296814/2200000 [00:36<03:52, 8176.12it/s]Traceback (most recent call last):
  File "config.py", line 144, in <module>
    tf.app.run()
  File "C:\Users\chchauha\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 126, in run
    _sys.exit(main(argv))
  File "config.py", line 127, in main
    prepro(config)
  File "F:\Synapse\QANet-master\prepro.py", line 287, in prepro
    word_counter, "word", emb_file=word_emb_file, size=config.glove_word_size, vec_size=config.glove_dim)
  File "F:\Synapse\QANet-master\prepro.py", line 99, in get_embedding
    vector = list(map(float, array[-vec_size:]))
ValueError: could not convert string to float: 'sania'**

**Comment by localminimum** [comment]
Hi @charu-iitm , are you using a custom word vector? If so, please make sure that each line contains only 1 word.
